#ifndef UVS_LIMIT_HPP
#define UVS_LIMIT_HPP

#define LINEAR_SPEED 0.2f
#define ANGULAR_SPEED 1.0f
#define ARM_ANGLE_MIN 49U
#define ARM_ANGLE_MAX 4000U
#define ARM_ANGLE_STEP 10U

#endif //UVS_LIMIT_HPP